version: 2.1
#####################################################
# Runner config
#####################################################
defaults: &defaults
  docker:
    - image: maven:3.3-jdk-8
  working_directory: ~/project


#####################################################
# Jobs
#####################################################
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      
      - run:
          command: |
            mvn clean package
          
      - persist_to_workspace:
          root: ~/project
          paths:
          - ./

  
#####################################################
# Workflow
#####################################################
workflows:
  version: 2
  
  build_project:
    jobs:
      - build

